export const columns = [
    { field: 'id', headerName: 'id', width: 160 },
     { field: 'cdrid', headerName: 'CDRID', width: 160 },
     { field: 'message_id', headerName: 'MessageID', width: 160 },
    { field: 'client', headerName: 'Client', width: 160 },
    {
      field: 'sender_id',
      headerName: 'Sender',
      width: 160,
    },
    {
      field: 'message_text',
      headerName: 'Message Text',
      width: 160,
  
    },
    { field: 'status', headerName: 'Status', width: 160 },
    { field: 'destination', headerName: 'Destination', width: 160 },
    { field: 'operator', headerName: 'Operator', width: 160 },
    { field: 'country', headerName: 'Country', width: 160 },
    { field: 'delivery_status', headerName: 'DeliveryStatus', width: 160 },
    { field: 'terminator_message_id', headerName: 'TerminatorMessId', width: 160 },
    { field: 'date_recieved', headerName: 'DateRecieved', width: 160 },
    { field: 'date_sent', headerName: 'DateSent', width: 160 },
    { field: 'fake', headerName: 'Fake', width: 160 },
  ];
  
  
  export const rows =[
      {
        "id": 1,
        "cdrid":2,
        "message_id": 4,
        "client": "Prof.",
        "sender_id": "Microsoft",
        "message_text": "Ut perferendis enim velit libero possimus. Dolores est dolor quibusdam reiciendis ab. Voluptas consequuntur vel praesentium ut quos. Consectetur est omnis illum quo dolore.",
        "status": "Nesciunt necessitatibus omnis maxime eaque minima. Est fuga provident beatae reprehenderit cumque reiciendis.",
        "destination": "Fugit ratione error natus sint consequatur. Sed natus qui eius est. Eum quia dolores at nam sed.",
        "operator": "Dolore ut voluptatem incidunt sunt. Minima deleniti et voluptas est consequatur quaerat. Explicabo ex sunt placeat eaque sit. Laudantium velit fugiat vitae sint.",
        "country": "Aut aut voluptatem eos quae est repellat. Officiis aut quasi eveniet mollitia nobis. Eaque voluptatum velit pariatur quidem temporibus. Saepe totam laboriosam quia repellendus non neque.",
        "delivery_status": "Excepturi rerum dolor eius facere quia. Et incidunt aut ullam omnis earum. Laboriosam omnis facilis unde tenetur similique voluptatum.",
        "terminator_message_id": 6,
        "date_recieved": "2017-01-25",
        "date_sent": "1976-06-22",
        "date_dlr": "1993-02-15",
        "fake": 0,
        "created_at": "2022-05-11T08:02:18.000000Z",
        "updated_at": "2022-05-11T08:02:18.000000Z",
        "totalsms":500,
        "percentage":30
  
      },
      {
        "id": 2,
        "cdrid":4,
        "message_id": 0,
        "client": "Dr.",
        "sender_id": "Facebook",
        "message_text": "Eius omnis aut voluptas beatae enim non atque. Et occaecati quia eius. Aspernatur libero rerum sint nulla perferendis ipsa ipsa. Ut ea quod magni in aut minima at.",
        "status": "Laudantium tempore expedita et et tempore provident necessitatibus. Voluptatem non dolores consequatur voluptas aut fugit. Quo perferendis quia repellat.",
        "destination": "Molestiae distinctio optio non. Nisi consequatur provident sint odio occaecati ipsa non dolorum.",
        "operator": "Esse aperiam minus repellendus error eius. Ad in alias et culpa quos.",
        "country": "Ad est eos impedit ab velit ut commodi. Aperiam alias qui et adipisci vitae enim suscipit. Commodi aspernatur qui eos.",
        "delivery_status": "Quasi vitae soluta debitis quia fugiat magnam. Qui incidunt eos magni nemo ullam recusandae impedit. Optio maiores qui non nihil.",
        "terminator_message_id": 4,
        "date_recieved": "1989-04-30",
        "date_sent": "2018-08-15",
        "date_dlr": "2008-01-16",
        "fake": 1,
        "created_at": "2022-05-11T08:02:18.000000Z",
        "updated_at": "2022-05-11T08:02:18.000000Z",
        "totalsms":200,
        "percentage":50
      },
      {
        "id": 3,
        "cdrid":4,
        "message_id": 0,
        "client": "Dr.",
        "sender_id": "Google",
        "message_text": "Eius omnis aut voluptas beatae enim non atque. Et occaecati quia eius. Aspernatur libero rerum sint nulla perferendis ipsa ipsa. Ut ea quod magni in aut minima at.",
        "status": "Laudantium tempore expedita et et tempore provident necessitatibus. Voluptatem non dolores consequatur voluptas aut fugit. Quo perferendis quia repellat.",
        "destination": "Molestiae distinctio optio non. Nisi consequatur provident sint odio occaecati ipsa non dolorum.",
        "operator": "Esse aperiam minus repellendus error eius. Ad in alias et culpa quos.",
        "country": "Ad est eos impedit ab velit ut commodi. Aperiam alias qui et adipisci vitae enim suscipit. Commodi aspernatur qui eos.",
        "delivery_status": "Quasi vitae soluta debitis quia fugiat magnam. Qui incidunt eos magni nemo ullam recusandae impedit. Optio maiores qui non nihil.",
        "terminator_message_id": 4,
        "date_recieved": "1989-04-30",
        "date_sent": "2018-08-15",
        "date_dlr": "2008-01-16",
        "fake": 1,
        "created_at": "2022-05-11T08:02:18.000000Z",
        "updated_at": "2022-05-11T08:02:18.000000Z",
        "totalsms":400,
        "percentage":90
      },
      {
        "id": 4,
        "cdrid":4,
        "message_id": 0,
        "client": "Dr.",
        "sender_id": "Outlook",
        "message_text": "Eius omnis aut voluptas beatae enim non atque. Et occaecati quia eius. Aspernatur libero rerum sint nulla perferendis ipsa ipsa. Ut ea quod magni in aut minima at.",
        "status": "Laudantium tempore expedita et et tempore provident necessitatibus. Voluptatem non dolores consequatur voluptas aut fugit. Quo perferendis quia repellat.",
        "destination": "Molestiae distinctio optio non. Nisi consequatur provident sint odio occaecati ipsa non dolorum.",
        "operator": "Esse aperiam minus repellendus error eius. Ad in alias et culpa quos.",
        "country": "Ad est eos impedit ab velit ut commodi. Aperiam alias qui et adipisci vitae enim suscipit. Commodi aspernatur qui eos.",
        "delivery_status": "Quasi vitae soluta debitis quia fugiat magnam. Qui incidunt eos magni nemo ullam recusandae impedit. Optio maiores qui non nihil.",
        "terminator_message_id": 4,
        "date_recieved": "1989-04-30",
        "date_sent": "2018-08-15",
        "date_dlr": "2008-01-16",
        "fake": 1,
        "created_at": "2022-05-11T08:02:18.000000Z",
        "updated_at": "2022-05-11T08:02:18.000000Z",
        "totalsms":1000,
        "percentage":10
      },
      {
        "id": 5,
        "cdrid":4,
        "message_id": 0,
        "client": "Dr.",
        "sender_id": "Instagram",
        "message_text": "Eius omnis aut voluptas beatae enim non atque. Et occaecati quia eius. Aspernatur libero rerum sint nulla perferendis ipsa ipsa. Ut ea quod magni in aut minima at.",
        "status": "Laudantium tempore expedita et et tempore provident necessitatibus. Voluptatem non dolores consequatur voluptas aut fugit. Quo perferendis quia repellat.",
        "destination": "Molestiae distinctio optio non. Nisi consequatur provident sint odio occaecati ipsa non dolorum.",
        "operator": "Esse aperiam minus repellendus error eius. Ad in alias et culpa quos.",
        "country": "Ad est eos impedit ab velit ut commodi. Aperiam alias qui et adipisci vitae enim suscipit. Commodi aspernatur qui eos.",
        "delivery_status": "Quasi vitae soluta debitis quia fugiat magnam. Qui incidunt eos magni nemo ullam recusandae impedit. Optio maiores qui non nihil.",
        "terminator_message_id": 4,
        "date_recieved": "1989-04-30",
        "date_sent": "2018-08-15",
        "date_dlr": "2008-01-16",
        "fake": 1,
        "created_at": "2022-05-11T08:02:18.000000Z",
        "updated_at": "2022-05-11T08:02:18.000000Z",
        "totalsms":2212,
        "percentage":77
      },
      {
        "id": 6,
        "cdrid":4,
        "message_id": 0,
        "client": "Dr.",
        "sender_id": "Twitter",
        "message_text": "Eius omnis aut voluptas beatae enim non atque. Et occaecati quia eius. Aspernatur libero rerum sint nulla perferendis ipsa ipsa. Ut ea quod magni in aut minima at.",
        "status": "Laudantium tempore expedita et et tempore provident necessitatibus. Voluptatem non dolores consequatur voluptas aut fugit. Quo perferendis quia repellat.",
        "destination": "Molestiae distinctio optio non. Nisi consequatur provident sint odio occaecati ipsa non dolorum.",
        "operator": "Esse aperiam minus repellendus error eius. Ad in alias et culpa quos.",
        "country": "Ad est eos impedit ab velit ut commodi. Aperiam alias qui et adipisci vitae enim suscipit. Commodi aspernatur qui eos.",
        "delivery_status": "Quasi vitae soluta debitis quia fugiat magnam. Qui incidunt eos magni nemo ullam recusandae impedit. Optio maiores qui non nihil.",
        "terminator_message_id": 4,
        "date_recieved": "1989-04-30",
        "date_sent": "2018-08-15",
        "date_dlr": "2008-01-16",
        "fake": 1,
        "created_at": "2022-05-11T08:02:18.000000Z",
        "updated_at": "2022-05-11T08:02:18.000000Z",
        "totalsms":1333,
        "percentage":40
      }
    ]